import type { ModelInfo } from "../model.js"

export type AgenticaModelId = keyof typeof agenticaModels

export const agenticaDefaultModelId: AgenticaModelId = "deca-coder-flash"

export const AGENTICA_DEFAULT_BASE_URL = "https://api.genlabs.dev/agentica/v1" as const

export const agenticaModels = {
	// Free Models
	"deca-2.5-pro-low": {
		maxTokens: 128_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		inputPrice: 0,
		outputPrice: 0,
		description: "2.5 pro low",
		creditsMultiplier: 0, // Free model - 0x credits
		isFree: true,
	},
	"kimi-k2.5": { // kilocode_change
		maxTokens: 128_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		description: "Kimi K2.5 model",
		creditsMultiplier: 0,
		isFree: true,
	},
	"minimax-m2.1": { // kilocode_change
		maxTokens: 32_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		description: "Minimax M2.1 model",
		creditsMultiplier: 0,
		isFree: true,
	},
	"deepseek-v3.2": { // kilocode_change
		maxTokens: 64_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		description: "DeepSeek V3.2 (free)",
		creditsMultiplier: 0,
		isFree: true,
	},
	"glm-5": { // kilocode_change
		maxTokens: 128_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		description: "GLM 5 (free)",
		creditsMultiplier: 0,
		isFree: true,
	},
	"qwen3.5": { // kilocode_change
		maxTokens: 32_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		description: "Qwen 3.5 (free)",
		creditsMultiplier: 0,
		isFree: true,
	},
	"gpt-oss-120b": {
		maxTokens: 32_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		description: "GPT OSS 120B",
		creditsMultiplier: 0, // Free model - 0x credits
		isFree: true,
	},
	"deca-coder-flash": {
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		description: "Deca Coder Flash (routes via classification)",
		creditsMultiplier: 0, // Free model - 0x credits
		isFree: true,
	},
	// Paid-Free Models (OpenRouter)
	"minimax-m2.5": {
		maxTokens: 32_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0,
		outputPrice: 0,
		description: "Minimax M2.5 (paid plans only, no credit cost)",
		requiresPaidPlan: true,
	},
	// Premium Models (OpenRouter)
	"deca-2.5-pro-high": {
		maxTokens: 128_000,
		contextWindow: 200_000,
		supportsImages: false,
		supportsPromptCache: true,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		inputPrice: 0,
		outputPrice: 0,
		description: "2.5 pro high",
		creditsMultiplier: 0,
		isFree: true,
	},
	"claude-4.6-sonnet": { // kilocode_change
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 3.00,
		outputPrice: 15.00,
		description: "Claude 4.6 Sonnet",
	},
	"claude-4.6-opus": { // kilocode_change
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 5.00,
		outputPrice: 25.00,
		description: "Claude 4.6 Opus",
	},
	"gpt-5.3-codex": { // kilocode_change
		maxTokens: 128_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 1.75,
		outputPrice: 14.00,
		description: "GPT-5.3",
	},
	"gemini-3.1-pro": { // kilocode_change
		maxTokens: 64_000,
		contextWindow: 1_000_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 2.00,
		outputPrice: 12.00,
		description: "Gemini 3 Pro",
	},
	"gemini-3-pro": { // kilocode_change
		maxTokens: 64_000,
		contextWindow: 1_000_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 2.00,
		outputPrice: 12.00,
		description: "Gemini 3 Pro",
	},
	// kilocode_change - Premium Models (additional)
	"gemini-3-flash": { // kilocode_change
		maxTokens: 64_000,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 0.50,
		outputPrice: 3.00,
		description: "Gemini 3 Flash",
	},
	"gpt-5.1-codex-mini": { // kilocode_change
		maxTokens: 64_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.25,
		outputPrice: 2.00,
		description: "GPT-5.1 Codex Mini",
	},
	"grok-4": { // kilocode_change
		maxTokens: 128_000,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 3.00,
		outputPrice: 15.00,
		description: "Grok 4",
	},
	"grok-4.1-fast": { // kilocode_change
		maxTokens: 128_000,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 0.20,
		outputPrice: 0.50,
		description: "Grok 4.1 Fast",
	},
	"grok-code-fast-1": { // kilocode_change
		maxTokens: 64_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.20,
		outputPrice: 1.50,
		description: "Grok Code Fast 1",
	},
	"deca-2.5-mini": { // kilocode_change
		maxTokens: 64_000,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.50,
		outputPrice: 1.50,
		description: "2.5 mini premium model",
	},
} as const satisfies Record<string, ModelInfo>
